"use client";

import { AdminPageTitle } from "@/components/admin/Title";
import CardSection from "@/components/admin/CardSection";
import {
  SvgActivity,
  SvgCode,
  SvgCpu,
  SvgExternalLink,
  SvgFileText,
  SvgGlobe,
  SvgHardDrive,
  SvgSearch,
  SvgServer,
} from "@opal/icons";
import SvgMcp from "@opal/icons/mcp";
import type { IconProps } from "@opal/types";

interface ServiceCardProps {
  name: string;
  description: string;
  icon: React.FunctionComponent<IconProps>;
  category: string;
  url?: string;
  urlLabel?: string;
  port?: string;
  internal?: boolean;
  credentials?: string;
}

const services: ServiceCardProps[] = [
  {
    name: "Phoenix LLM Observability",
    description:
      "Arize Phoenix provides LLM tracing, token usage dashboards, cost tracking, and latency analysis. Monitor all AI interactions in real-time.",
    icon: SvgActivity,
    category: "Observability",
    url: "/phoenix/",
    urlLabel: "Open Phoenix Dashboard",
    port: "6006",
  },
  {
    name: "Office MCP Server",
    description:
      "Generate PowerPoint presentations, Word documents, and PDFs via MCP protocol. Provides 91 tools: 37 PPT (ppt_*) + 54 DOCX (docx_*) including PDF export.",
    icon: SvgFileText,
    category: "MCP Tools",
    url: undefined,
    urlLabel: "Internal MCP endpoint",
    port: "8100",
    internal: true,
  },
  {
    name: "SmartSearch AI",
    description:
      "Perplexica-based AI web search engine. Provides real-time web search with AI-powered answer synthesis and source citations.",
    icon: SvgSearch,
    category: "AI Search",
    url: "http://localhost:3001",
    urlLabel: "Open SmartSearch",
    port: "3000/3001",
  },
  {
    name: "MinIO Object Storage",
    description:
      "S3-compatible object storage for file uploads, document attachments, and generated artifacts. Stores all user-uploaded files and AI-generated outputs.",
    icon: SvgHardDrive,
    category: "Storage",
    url: "http://localhost:9005",
    urlLabel: "Open MinIO Console",
    port: "9000/9001",
    credentials: "minioadmin / minioadmin",
  },
  {
    name: "GPUStack",
    description:
      "Local GPU inference server for running open-source LLMs (LLaMA, Mistral, etc.) and embedding models. Manages GPU resources and model deployments.",
    icon: SvgCpu,
    category: "AI Infrastructure",
    url: "http://localhost:9080",
    urlLabel: "Open GPUStack Dashboard",
    port: "9080",
    credentials: "admin / :mO67xHQ$c$h&",
  },
  {
    name: "Code Interpreter",
    description:
      "Sandboxed Python execution environment for running code generated by AI assistants. Supports data analysis, visualization, and file processing.",
    icon: SvgCode,
    category: "AI Tools",
    port: "8000",
    internal: true,
  },
  {
    name: "MCP Tools Server",
    description:
      "Model Context Protocol server providing DuckDuckGo search, web fetch, Brave search, ArXiv paper search, sequential thinking, and filesystem access tools.",
    icon: SvgMcp,
    category: "MCP Tools",
    port: "Various",
    internal: true,
  },
  {
    name: "Vespa Search Index",
    description:
      "High-performance vector and text search engine. Handles document indexing, hybrid search (BM25 + embeddings), and real-time index updates.",
    icon: SvgServer,
    category: "Infrastructure",
    port: "8081/19071",
    internal: true,
  },
  {
    name: "Model Servers",
    description:
      "Inference and indexing model servers for running embedding models and reranking models. Powers semantic search and document understanding.",
    icon: SvgCpu,
    category: "AI Infrastructure",
    port: "9000/9090",
    internal: true,
  },
  {
    name: "API Server",
    description:
      "Core backend API handling authentication, chat, document management, assistant orchestration, and all platform business logic.",
    icon: SvgServer,
    category: "Core",
    port: "8080",
    internal: true,
  },
  {
    name: "Background Worker",
    description:
      "Processes async tasks: document indexing, connector syncing, embedding generation, scheduled jobs, and workflow execution.",
    icon: SvgGlobe,
    category: "Core",
    port: "—",
    internal: true,
  },
];

const categoryColors: Record<string, string> = {
  Observability: "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300",
  "MCP Tools": "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300",
  "AI Search": "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300",
  Storage: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300",
  "AI Infrastructure": "bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-300",
  "AI Tools": "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-300",
  Infrastructure: "bg-slate-100 text-slate-700 dark:bg-slate-900/30 dark:text-slate-300",
  Core: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300",
};

function ServiceCard({
  name,
  description,
  icon: Icon,
  category,
  url,
  urlLabel,
  port,
  internal,
  credentials,
}: ServiceCardProps) {
  return (
    <CardSection className="flex flex-col gap-3 h-full">
      <div className="flex items-start justify-between gap-2">
        <div className="flex items-center gap-3">
          <div
            className="flex items-center justify-center w-10 h-10 rounded-lg shrink-0"
            style={{ backgroundColor: "var(--virtualai-accent-subtle, rgba(99,102,241,0.1))" }}
          >
            <Icon
              size={20}
              style={{ color: "var(--virtualai-accent, var(--theme-primary-05))" }}
            />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-text-900">{name}</h3>
            <span
              className={`inline-block mt-0.5 px-2 py-0.5 rounded-full text-xs font-medium ${categoryColors[category] || "bg-gray-100 text-gray-700"}`}
            >
              {category}
            </span>
          </div>
        </div>
        {port && (
          <span className="text-xs text-text-500 font-mono shrink-0">
            :{port}
          </span>
        )}
      </div>

      <p className="text-xs text-text-600 leading-relaxed flex-grow">
        {description}
      </p>

      {credentials && (
        <div className="px-2.5 py-1.5 rounded-md bg-background-neutral-02 border border-border-01">
          <span className="text-2xs text-text-400 uppercase tracking-wider font-medium">
            Credentials
          </span>
          <p className="text-xs font-mono text-text-600 mt-0.5">{credentials}</p>
        </div>
      )}

      <div className="mt-auto pt-2 border-t border-border-light">
        {url && !internal ? (
          <a
            href={url}
            target={url.startsWith("/") ? undefined : "_blank"}
            rel={url.startsWith("/") ? undefined : "noopener noreferrer"}
            className="inline-flex items-center gap-1.5 text-xs font-medium transition-colors"
            style={{ color: "var(--virtualai-accent, var(--theme-primary-05))" }}
          >
            <SvgExternalLink size={14} />
            {urlLabel || "Open"}
          </a>
        ) : (
          <span className="inline-flex items-center gap-1.5 text-xs text-text-400">
            <SvgServer size={14} />
            {internal ? "Internal service" : "No web UI"}
          </span>
        )}
      </div>
    </CardSection>
  );
}

export default function Page() {
  return (
    <>
      <AdminPageTitle
        title="Platform Services"
        icon={SvgServer}
        description="Overview of all platform services, their purpose, and access links."
      />

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        {services.map((service) => (
          <ServiceCard key={service.name} {...service} />
        ))}
      </div>
    </>
  );
}
